server:
  port: 8090
mybatis-plus:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.zilansw.zilanshop.pojo

spring:
  datasource:
    url: jdbc:mysql://db.lightidc.com:10126/zilansw_shop?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8